<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contrat de credit</name>
   <tag></tag>
   <elementGuidId>76f721ed-b192-463b-94a3-fe8ec2cc4449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page-top']/div[2]/fieldset/legend/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Contrat de crédit&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cf2fe8ec-e77d-44c2-bd32-3515b387de3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-file</value>
      <webElementGuid>999049f9-f0eb-41b1-b512-2de8af8753b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc5f31d5-f6ed-40f9-a8c9-b56efd022c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Contrat de crédit</value>
      <webElementGuid>829d74cc-83ef-4eda-a825-b9eb2ebe242a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[@class=&quot;container&quot;]/fieldset[@class=&quot;scheduler-border&quot;]/legend[@class=&quot;scheduler-border&quot;]/i[@class=&quot;fa fa-file&quot;]</value>
      <webElementGuid>825fc2e6-aae6-4a17-9a47-b8c67d645495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div[2]/fieldset/legend/i</value>
      <webElementGuid>c3ecc992-eda1-49e5-b4ce-7ba84dbe8686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrat n° 28136161289 créé avec succès'])[1]/following::i[1]</value>
      <webElementGuid>ac8099a0-d3cd-4617-8491-2a46d1259345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprimer'])[1]/preceding::i[1]</value>
      <webElementGuid>6d0b843b-cb52-48b2-95d2-9418746d31ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enregistrer'])[1]/preceding::i[1]</value>
      <webElementGuid>34c6b832-6431-4d92-9f42-e0306e7e3630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contrat de crédit']/parent::*</value>
      <webElementGuid>32b4a4af-f978-40d5-98bb-386f55cf17c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend/i</value>
      <webElementGuid>e4fbb6c4-3e77-4811-851f-7628ce071da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = ' Contrat de crédit' or . = ' Contrat de crédit')]</value>
      <webElementGuid>bbfb27e2-81f6-4e07-bcd4-6829c66a1646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
