<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Jean_custom-control-labels</name>
   <tag></tag>
   <elementGuidId>99e16b97-e7a3-4c0b-9436-b944d7f3ec52</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;clients&quot;)/tbody[1]/tr[2]/td[1]/div[@class=&quot;center-align custom-control custom-checkbox mb-3&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='clients']/tbody/tr[2]/td/div/input</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;28136161289 DUCLOS Jean 236251&quot;i] >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>261519db-5c94-425c-ba75-7cf1e7809653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>884bb1b5-09f0-49a8-82d8-639e9f919d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>customControlValidation2</value>
      <webElementGuid>cdf2464f-163e-4946-a695-9b2ad0da0791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clients&quot;)/tbody[1]/tr[2]/td[1]/div[@class=&quot;center-align custom-control custom-checkbox mb-3&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>1d0f0c21-e231-4a5f-89ae-c483e95506b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='clients']/tbody/tr[2]/td/div/input</value>
      <webElementGuid>e9d02104-7a43-4f89-bdf9-ceb639d3a55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/input</value>
      <webElementGuid>4098774b-8c53-4350-9afd-1fc43a6ab448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
