<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Resume du contrat</name>
   <tag></tag>
   <elementGuidId>241d9c9a-afa8-4b2c-9213-e9285fed0824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page-top']/div[2]/fieldset/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Résumé du contrat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>81be6c6f-227a-4082-b7c1-40521f10ec81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Résumé du contrat</value>
      <webElementGuid>a37bf1a6-d367-48d4-9ff4-664b8d14787d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[@class=&quot;container&quot;]/fieldset[@class=&quot;scheduler-border&quot;]/p[3]</value>
      <webElementGuid>ce0070d3-1970-4923-937c-191006192384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div[2]/fieldset/p[3]</value>
      <webElementGuid>5322d9d4-ad88-4d10-842e-390f96cabef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrat n° 28136161289 créé avec succès'])[1]/following::p[3]</value>
      <webElementGuid>ebc2a2fb-1b44-4c19-95fb-cc67da36f0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprimer'])[1]/preceding::p[5]</value>
      <webElementGuid>13ec62f5-6e7d-4c73-ba4d-d4d0f74562f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enregistrer'])[1]/preceding::p[5]</value>
      <webElementGuid>6db2f34c-e6c6-4e77-9831-c26b48a462b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Résumé du contrat']/parent::*</value>
      <webElementGuid>9d39cd74-131c-47d0-a7e3-9e003c34baa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>e04e70d3-49c5-4a29-bddc-cde16825d01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Résumé du contrat' or . = 'Résumé du contrat')]</value>
      <webElementGuid>9b51559e-2997-4288-a8b9-a9443cdbeeaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
