<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_A</name>
   <tag></tag>
   <elementGuidId>5a67f0e5-e3dc-402e-93ea-de247646688c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='form_simulation_categorie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_simulation_categorie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categorie&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e74e624-15cb-4183-9669-ed42a977c4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_simulation_categorie</value>
      <webElementGuid>285f9571-e799-41ae-bf17-486af1394fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categorie</value>
      <webElementGuid>b11a912f-7953-437c-b070-127c2872a8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dd422e7a-fe00-4150-b7ee-48c401b5ea86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                A
                B
            </value>
      <webElementGuid>9496d02b-8e45-4434-a5b9-c6d1fe67a265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_simulation_categorie&quot;)</value>
      <webElementGuid>1a28a8a2-8a26-43a1-a0d4-b48d5979dd3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form_simulation_categorie']</value>
      <webElementGuid>2e7b46ec-af7a-4d06-aa58-36a2e1453120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contract']/form/fieldset/div[5]/select</value>
      <webElementGuid>08b4567e-7e8e-4442-8113-cc7a5e6b256a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categorie'])[1]/following::select[1]</value>
      <webElementGuid>00327bf7-8a35-490b-a4ea-bd3e861a4b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La durée du contrat est comprise entre 12 et 48 mois'])[1]/following::select[1]</value>
      <webElementGuid>0ec16689-8b6b-42b6-ba3d-56ede1174d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cout credit'])[1]/preceding::select[1]</value>
      <webElementGuid>493174b0-c995-4ead-a644-a3390fd1b8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>80d66885-7813-43be-982b-6ad909d71638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'form_simulation_categorie' and @name = 'categorie' and (text() = '
                A
                B
            ' or . = '
                A
                B
            ')]</value>
      <webElementGuid>557bf638-bbd0-43b5-9310-947c6b44121a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
