name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '9.3.1'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/Authentification" -apiKey= ${{ secrets.API_KEY }} -browserType=Chrome -dataFile="CA_JDD_Authentification_V1.0.xlsx"  --config -webui.autoUpdateDrivers=true'